# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GSDAnalysis
                                 A QGIS plugin
 GSD analysis and visualisation for aerial mapping missions
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-05-31
        copyright            : (C) 2019 by Jonas Hener / Avy BV
        email                : jonas.hener@web.de
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GSDAnalysis class from file GSDAnalysis.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .gsd_analysis import GSDAnalysis
    return GSDAnalysis(iface)
